In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [7]:
mean_a = a.mean(axis = 0)

In [8]:
print(mean_a)

[2.  8.4]


In [9]:
a_centered = a - mean_a

In [10]:
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [13]:
b = a_centered[:, :1].copy()
print(b)
print(a_centered)

[[-1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [-1.]]
[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [15]:
c = a_centered[:, 1:].copy()
print(c)

[[-2.4]
 [-0.4]
 [ 2.6]
 [ 1.6]
 [-1.4]]


In [17]:
c_t = c.T

In [20]:
print(c_t)

[[-2.4 -0.4  2.6  1.6 -1.4]]


In [21]:
a_centered_sp = c_t @ b

In [22]:
print(a_centered_sp)

[[8.]]


In [23]:
r = np.linalg.matrix_rank(a)
print(r)

2


In [24]:
n = a.shape
print(n)

(5, 2)


In [27]:
N = n[:1]
print(N)

(5,)


In [28]:
cov1 = a_centered_sp/(N[0] - 1)
print(cov1)

[[2.]]


In [29]:
a_t = a.T
print(a_t)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [30]:
cov = np.cov(a_t)
print(cov)

[[1.  2. ]
 [2.  4.3]]


In [31]:
cov2 = cov[1, 0]
print(cov2)

2.0
